version: '3.8'

services:
  db:
    image: postgres:13
    container_name: fall_detection_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fall_detection
      TZ: Asia/Shanghai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: .
    container_name: fall_detection_backend
    depends_on:
      - db
      - emqx
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: fall_detection
      DB_SSL: "false"
      JWT_SECRET: your_secure_jwt_secret_key_here
      JWT_REFRESH_SECRET: your_secure_refresh_secret_key_here
      MQTT_BROKER: mqtt://emqx:1883
      NODE_ENV: development
      CORS_ORIGIN: "*"
      UPLOAD_DIR: uploads
      PUBLIC_DIR: public
    ports:
      - "3000:3000"
    volumes:
      - uploads_data:/usr/src/app/uploads
      - public_data:/usr/src/app/public
    command: npx nodemon src/app.js
    restart: unless-stopped

  emqx:
    image: emqx:5
    container_name: fall_detection_emqx
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    environment:
      EMQX_LOG__LEVEL: warning
      EMQX_DASHBOARD__DEFAULT_USERNAME: admin
      EMQX_DASHBOARD__DEFAULT_PASSWORD: public
    volumes:
      - emqx_data:/opt/emqx/data
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    container_name: fall_detection_nginx
    depends_on:
      - backend
      - emqx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

volumes:
  postgres_data:
  emqx_data:
  uploads_data:
  public_data: